### ISSUE TITLE
why I got this hint ？

### ISSUE THREAD

**Issue by iphyer** [manugarri/keras_monet#4]
```
/home/XXX/Downloads/keras_monet-master/lstm_image_generation.py(69)<module>()
-> text = np.apply_along_axis(rgb_to_hex, 2, text)
(Pdb) 

```

**Comment by kdsull** [comment]
Well, I commented out 'import pdb' part, but I get an error message,

> loading image download (7).jpg
> total chars: 1000
> nb sequences: 91850
> Vectorization...
> Build model...
> Traceback (most recent call last):
>   File "lstm_image_generation.py", line 99, in <module>
>     model.add(LSTM(len(chars), 512, return_sequences=True))
>   File "/home/kdsull/Dev/keras-tf/keras/models.py", line 106, in add
>     raise Exception('The first layer in a Sequential model must '
> Exception: The first layer in a Sequential model must get an `input_shape` or `batch_input_shape` argument.

Very interesting example of Char RNN, and I really would like to the result myself ! I'd appreciate if you could look into this error message.

**Comment by iphyer** [comment]
@kdsull Thank you!
